name: music_box
description: Banjo and Guitar app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.0.3
  google_fonts: 2.2.0

dev_dependencies:
  flutter_launcher_icons: 0.9.2
  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/banjo_nav.svg
    - assets/guitar_nav.svg

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/icon.png
